# Generated by Django 4.2.14 on 2024-07-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=100)),
                ('entity', models.CharField(max_length=200)),
                ('activity', models.CharField(max_length=200)),
                ('agent', models.CharField(max_length=200)),
                ('generated_at_time', models.DateTimeField(auto_now_add=True)),
                ('used', models.CharField(blank=True, max_length=200, null=True)),
                ('was_influenced_by', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
